### ISSUE TITLE
Add Math Functions

### ISSUE THREAD

**Issue by hatlesshacker** [hatlesshacker/LibFalcon#1]
Add the necessary math functions which Hobby kernels make use of.

**Comment by ShubhamAvasthi** [comment]
Can you please detail about what additions do you want in the code and where?

**Comment by hatlesshacker** [comment]
At this moment, just about any standardized Math function would be great; Thanks for your consideration. :-)

**Comment by JamieLuo** [comment]
It seems, contributors forgot to declare the function to the header file.

**Comment by gnuille** [comment]
Is there any purpose for having a file add.c, div.c etc.. ?

**Comment by Ad-S** [comment]
is this issue still active

**Comment by gnuille** [comment]
i don't know :/

**Comment by hatlesshacker** [comment]
Sorry,
I have ben busy with few other projects of mine, and therefore was not able to spend time with this project.

Every function that's might aid in the development of simple kernels, and does not impose further restrictions upon the kernel developer are required here.

@teleportex trivial functions like add & div are there for the sake of completeness of the library. Kernel-specific functions are more than needed
